### ISSUE TITLE
Someting not right with unit tests/groovy

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#31]
About the time we merged in the new unit test stuff and I added the groovy stuff I notices this.

I have to tell my ide to rebuild the project or refresh when this happens. Something is not cleaning up well.

DEBUG [MigrationStage:1]: Scanned 3 rows and matched 3
java.lang.RuntimeException: Failed to create keyspace for myks
    at org.usergrid.vx.experimental.CassandraRunner.maybeCreateKeyspace(CassandraRunner.java:117)
    at org.usergrid.vx.experimental.CassandraRunner.run(CassandraRunner.java:90)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily schema_columnfamilies
    at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:348)
    at org.apache.cassandra.service.MigrationManager.announce(MigrationManager.java:238)
    at org.apache.cassandra.service.MigrationManager.announceNewKeyspace(MigrationManager.java:171)
    at org.usergrid.vx.experimental.CassandraRunner.maybeCreateKeyspace(CassandraRunner.java:109)
    ... 7 more
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily schema_columnfamilies
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:344)
    ... 10 more
Caused by: java.lang.AssertionError: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily schema_columnfamilies
    at org.apache.cassandra.cql3.QueryProcessor.resultify(QueryProcessor.java:177)
    at org.apache.cassandra.config.KSMetaData.deserializeColumnFamilies(KSMetaData.java:302)
    at org.apache.cassandra.db.DefsTable.mergeColumnFamilies(DefsTable.java:414)
    at org.apache.cassandra.db.DefsTable.mergeSchema(DefsTable.java:327)
    at org.apache.cassandra.service.MigrationManager$1.call(MigrationManager.java:256)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily schema_columnfamilies
    at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamily(ThriftValidation.java:112)
    at org.apache.cassandra.cql3.statements.SelectStatement$RawStatement.prepare(SelectStatement.java:973)
    at org.apache.cassandra.cql3.QueryProcessor.getStatement(QueryProcessor.java:245)
    at org.apache.cassandra.cql3.QueryProcessor.resultify(QueryProcessor.java:171)
    ... 9 more
ERROR [Thread-2]: In shutdownHook
INFO  [Thread-2]: Stopping IntravertDeamon
java.lang.NullPointerException
    at org.usergrid.vx.server.IntravertDeamon.stop(IntravertDeamon.java:47)
    at org.apache.cassandra.service.CassandraDaemon.deactivate(CassandraDaemon.java:425)
    at org.usergrid.vx.experimental.CassandraRunner.stopCassandra(CassandraRunner.java:196)
    at org.usergrid.vx.experimental.CassandraRunner.access$1(CassandraRunner.java:194)
    at org.usergrid.vx.experimental.CassandraRunner$2.run(CassandraRunner.java:186)
DEBUG [FlushWriter:1]: Renaming /tmp/intra_data/system/local/system-local-tmp-ia-2-Statistics.db to /tmp/intra_data/system/local/system-local-ia-2-Statistics.db
DEBUG [FlushWriter:1]: Renaming /tmp/intra_data/system/local/system-local-tmp-ia-2-Index.db to /tmp/intra_data/system/local/system-local-ia-2-Index.db
DEBUG [FlushWriter:1]: Renaming /tmp/intra_data/system/local/system-local-tmp-ia-2-Filter.db to /tmp/intra_data/system/local/system-local-ia-2-Filter.db
DEBUG [FlushWriter:1]: Renaming /tmp/intra_data/system/local/system-local-tmp-ia-2-TOC.txt to /tmp/intra_data/system/local/system-local-ia-2-TOC.txt
DEBUG [FlushWriter:1]: Renaming /tmp/intra_data/system/local/system-local-tmp-ia-2-CompressionInfo.db to /tmp/intra_data/system/local/system-local-ia-2-CompressionInfo.db
DEBUG [FlushWriter:1]: Renaming /tmp/intra_data/system/local/system-local-tmp-ia-2-Data.db to /tmp/intra_data/system/local/system-local-ia-2-Data.db
INFO  [FlushWriter:1]: Completed flushing /tmp/intra_data/system/local/system-local-ia-2-Data.db (75 bytes) for commitlog position ReplayPosition(segmentId=1356904631739, position=47233)
DEBUG [FlushWriter:1]: Creating IntervalNode from [[DecoratedKey(-7564491331177403445, 6c6f63616c), DecoratedKey(-7564491331177403445, 6c6f63616c)](SSTableReader%28path='/tmp/intra_data/system/local/system-local-ia-1-Data.db'%29), [DecoratedKey(-7564491331177403445, 6c6f63616c), DecoratedKey(-7564491331177403445, 6c6f63616c)](SSTableReader%28path='/tmp/intra_data/system/local/system-local-ia-2-Data.db'%29)]
DEBUG [FlushWriter:1]: adding /tmp/intra_data/system/local/system-local-ia-2 to list of files tracked for system.local
DEBUG [FlushWriter:1]: Scheduling a background task check for system.local with SizeTieredCompactionStrategy
DEBUG [CompactionExecutor:2]: Checking system.local
DEBUG [COMMIT-LOG-WRITER]: discard completed log segments for ReplayPosition(segmentId=1356904631739, position=47233), column family 7ad54392-bcdd-35a6-8417-4e047860b377
DEBUG [COMMIT-LOG-WRITER]: Not safe to delete commit log CommitLogSegment(/tmp/intra_log/CommitLog-2-1356904631739.log); dirty is <deleted> (45f5b360-24bc-3f83-a363-1034ea4fa697), <deleted> (b0f22357-4458-3cdb-9631-c43e59ce3676), ; hasNext: false
DEBUG [pool-1-thread-1]: Setting tokens to [-9146897894645541148]
ERROR [pool-1-thread-1]: Exception encountered during startup
java.lang.AssertionError: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily local
    at org.apache.cassandra.cql3.QueryProcessor.processInternal(QueryProcessor.java:163)
    at org.apache.cassandra.db.SystemTable.updateTokens(SystemTable.java:254)
    at org.apache.cassandra.service.StorageService.setTokens(StorageService.java:196)
    at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:733)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:501)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:398)
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:305)
    at org.usergrid.vx.server.IntravertDeamon.setup(IntravertDeamon.java:29)
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:393)
    at org.usergrid.vx.experimental.CassandraRunner$1.run(CassandraRunner.java:172)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily local
    at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamily(ThriftValidation.java:112)
    at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamily(ThriftValidation.java:88)
    at org.apache.cassandra.cql3.statements.UpdateStatement.prepare(UpdateStatement.java:327)
    at org.apache.cassandra.cql3.statements.UpdateStatement.prepare(UpdateStatement.java:406)
    at org.apache.cassandra.cql3.QueryProcessor.getStatement(QueryProcessor.java:245)
    at org.apache.cassandra.cql3.QueryProcessor.processInternal(QueryProcessor.java:149)
    ... 12 more
java.lang.AssertionError: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily local
    at org.apache.cassandra.cql3.QueryProcessor.processInternal(QueryProcessor.java:163)
    at org.apache.cassandra.db.SystemTable.updateTokens(SystemTable.java:254)
    at org.apache.cassandra.service.StorageService.setTokens(StorageService.java:196)
    at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:733)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:501)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:398)
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:305)
    at org.usergrid.vx.server.IntravertDeamon.setup(IntravertDeamon.java:29)
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:393)
    at org.usergrid.vx.experimental.CassandraRunner$1.run(CassandraRunner.java:172)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily local
    at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamily(ThriftValidation.java:112)
    at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamily(ThriftValidation.java:88)
    at org.apache.cassandra.cql3.statements.UpdateStatement.prepare(UpdateStatement.java:327)
    at org.apache.cassandra.cql3.statements.UpdateStatement.prepare(UpdateStatement.java:406)
    at org.apache.cassandra.cql3.QueryProcessor.getStatement(QueryProcessor.java:245)
    at org.apache.cassandra.cql3.QueryProcessor.processInternal(QueryProcessor.java:149)
    ... 12 more
Exception encountered during startup: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily local
ERROR [MigrationStage:1]: Exception in thread Thread[MigrationStage:1,5,main]
java.lang.AssertionError: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily schema_columnfamilies
    at org.apache.cassandra.cql3.QueryProcessor.resultify(QueryProcessor.java:177)
    at org.apache.cassandra.config.KSMetaData.deserializeColumnFamilies(KSMetaData.java:302)
    at org.apache.cassandra.db.DefsTable.mergeColumnFamilies(DefsTable.java:414)
    at org.apache.cassandra.db.DefsTable.mergeSchema(DefsTable.java:327)
    at org.apache.cassandra.service.MigrationManager$1.call(MigrationManager.java:256)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.cassandra.exceptions.InvalidRequestException: unconfigured columnfamily schema_columnfamilies
    at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamily(ThriftValidation.java:112)
    at org.apache.cassandra.cql3.statements.SelectStatement$RawStatement.prepare(SelectStatement.java:973)
    at org.apache.cassandra.cql3.QueryProcessor.getStatement(QueryProcessor.java:245)
    at org.apache.cassandra.cql3.QueryProcessor.resultify(QueryProcessor.java:171)
    ... 9 more
ERROR [StorageServiceShutdownHook]: Exception in thread Thread[StorageServiceShutdownHook,5,main]
java.lang.NullPointerException
    at org.apache.cassandra.service.StorageService.stopRPCServer(StorageService.java:306)
    at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:462)
    at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
    at java.lang.Thread.run(Thread.java:722)
DEBUG [CompactionExecutor:2]: Compaction buckets are [[SSTableReader(path='/tmp/intra_data/system/local/system-local-ia-2-Data.db'), SSTableReader(path='/tmp/intra_data/system/local/system-local-ia-1-Data.db')]]
DEBUG [CompactionExecutor:2]: No tasks available

**Comment by zznate** [comment]
Which unit test caused this to happen?

**Comment by edwardcapriolo** [comment]
I am running the IntraServiceTest. In particular this happens after a failed test this happens. I sometimes in eclipse have to clean build and run N times to get a good run.

**Comment by zznate** [comment]
I added a shutdown hook to the CassandraRunner, is this still happening? (I cannot reproduce in IntelliJ)

**Comment by edwardcapriolo** [comment]
Seems better now.

**Comment by edwardcapriolo** [comment]
Actually still giving me problems. I might ttry another eclipse version,

**Comment by edwardcapriolo** [comment]
I think the issues were mostly from an older slower computer, though I bet if you run the tests on a busy jenkins box you can hit it as well. Will close for now.
